#! /bin/bash
MEMORY=$(free -m | awk 'NR==2{printf "\t%.2f%%\t", $3*100/$2 }')
CPU=$(top -bn1 | grep load | awk '{printf "%.2f%%\t\t\n", $(NF-1)}')
WEB=$(netstat -an|grep ':80\|:443'|wc -l)
DBCON=$(netstat -an| grep :5432|wc -l|awk '{printf "\t%s", $1}')
DT=$(date +%m%d-%H:%M | awk '{printf "%s\t", $1}')
echo "$DT$WEB$DBCON$MEMORY$CPU"

